### ISSUE TITLE
Add support for DomDomSoft Manga Reader program

### ISSUE THREAD

**Issue by blue-lightning** [riderkick/FMD#46]
You can download it from here: http://domdomsoft.com/

I try using the syntax 
      "E:\Setups\DomDomSoft Manga Reader\DomDomSoft Manga Reader.exe" "%PATH%"
in external path but it's not working. Instead, the first and last double quotation mark disappear; the program doesn't launch either.

**Comment by riderkick** [comment]
use:
E:\Setups\DomDomSoft Manga Reader\DomDomSoft Manga Reader.exe "%PATH%"

There is an issue with external program launcher, I need to separate the params.

**Comment by riderkick** [comment]
use:
```
E:\Setups\DomDomSoft Manga Reader\DomDomSoft Manga Reader.exe "%PATH%"
```
There is an issue with external program launcher, I need to separate the params.

**Comment by riderkick** [comment]
use:
```
E:\Setups\DomDomSoft Manga Reader\DomDomSoft Manga Reader.exe "%PATH%"
```
There is an issue with external program launcher, I need to separate the params.

**Comment by riderkick** [comment]
Fixed with this commit
https://github.com/riderkick/FMD/commit/31a711b520c89b0d8d5358c80318266458a16c02
https://github.com/riderkick/FMD/commit/c12ea69f133eaaf33915951090069331330b395b
https://github.com/riderkick/FMD/commit/e6dad8401678b1cb6defe74d3893cc5cf04330e4
https://github.com/riderkick/FMD/commit/534f04d85ee81393835ec2e272c9cd72cd8099f4

**Comment by blue-lightning** [comment]
Still not working. Maybe because DDS Manga Reader require elevated privillige ?

**Comment by riderkick** [comment]
It's working fine here with

    "E:\Setups\DomDomSoft Manga Reader\DomDomSoft Manga Reader.exe" "%PATH%"

Is there by any chance your path contain unicode character? if so, there is problem with passing unicode parameter. But the external program should be launched, it just can't pass the file to be opened.
If you save the file to cbz then you can leave it blank, and let fmd open it with default app associated with this extension.

**Comment by blue-lightning** [comment]
3 cases:
1) FMD with non-admin privilege: Nothing
2) FMD with admin privilege, parameter "%PATH%": DomDomSoft encouters an error
3) FMD with admin privilege, parameter "%PATH%%FCHAPTER%": Working, displays first downloaded chapter.

DomDomSoft's version is 1.4.3, FMD's is 0.9.16.1

**Comment by riderkick** [comment]
What is your path to the DMR? Can it work without admin?
How if you run DMR manually from run/cmd with that param `"DMR Path" "FIle/FolderPath"`
To what type is your downloaded file saved?
If you don't mind send me your config.ini,works.ini and favorites.ini

**Comment by blue-lightning** [comment]
The path is exactly as you see above: `"E:\Setups\DomDomSoft Manga Reader\DomDomSoft Manga Reader.exe"`. Not sure about the admin privilege, but everytime I start it it shoots a request so I guess it's needed. My manga storepath is also normal. I store manga as images, not compress pdf or cbr.

I just try running this command with a non-elevated command prompt, it asks for admin right and then launches DMR as expected:
`"E:\Setups\DomDomSoft Manga Reader\DomDomSoft Manga Reader.exe" "D:\Books\Comics\Mahou Tsukai no Yome"`

Config files are [here](http://www.mediafire.com/download/g4iiydkmfcz4z55/Desktop.7z)

**Comment by riderkick** [comment]
I've been fix the issue with admin privileges. But I still can't pass unicode character in parameter. I don't know, it can be limitation on fpc.

**Comment by blue-lightning** [comment]
Can unicode characters be converted to number code in code page UTF-8 or similar to be passed and then reconstructed on the command prompt ? Or maybe use PowerShell instead of Command Prompt ?

**Comment by riderkick** [comment]
It's already in UTF-8, I've been trying decode/encode without success. It seems it's the issue with fpc. I've been trying to use CreateProcessW ShellExecuteExW without success too.
http://forum.lazarus.freepascal.org/index.php?topic=22403.0
http://comments.gmane.org/gmane.comp.ide.lazarus.general/76593

I think that's why the original developers invent an option to remove all unicode character in.filename.

**Comment by blue-lightning** [comment]
Case 1 is fixed, but 2 is still not working. Launching DMR always results in error unless both %PATH% and %CHAPTER% is added.

**Comment by riderkick** [comment]
Launching DMR with "\" at the end causing error. It was the flaw of DMR, you should file the bug to them. Other app is fine with "\" at the end, and they should be.
I remove the the end pathdelim if chapter doesn't exist. But I forget to adjust it, if ```%CHAPTER%``` or file doesn't exist, then ```%PATH%``` should not end with pathdelim. I'll look at it.

**Comment by riderkick** [comment]
I think this commit should fix it.

**Comment by blue-lightning** [comment]
Confirm fixed. DMR isn't supported anymore so this bug will continue existing, sadly; but I can't find a good comic reader with long strip mode so just have to put up with it.

**Comment by riderkick** [comment]
What do you mean DMR isn't supported anymore?
The only bug left is passing unicode character.

**Comment by blue-lightning** [comment]
Forgot to add "by the developers". They've pretty much dropped the project. I'll edit the comment.

**Comment by riderkick** [comment]
I just fix the issue with unicode character.

**Comment by riderkick** [comment]
I just look at Honeyview forum, it seems the development is still alive and well, maybe you can ask them to add long strip view mode.
